name: unit testing lunox framework

on:
  pull_request:
    branches:
      - main
      - 1.x
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true
      - name: install node modules
        run: npm i
      - name: running unit testing and collect code coverage
        run: npm run test
